global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

storage:
  local:
    retention: 7d  # Retention period for local storage (7 days in this example)
